### ISSUE TITLE
Mention the fork

### ISSUE THREAD

**Issue by Mte90** [sksmatt/WordPress-Widgets-Helper-Class#9]
This class seems abandoned but people is still using it.

I am mantaing a fork with various patch and features: https://github.com/WPBP/Widgets-Helper

Maybe mention in the readme and archive this repo can be a solution to promote a better class :-)

**Comment by Mte90** [comment]
ping

**Comment by Mte90** [comment]
ping @sksmatt

**Comment by sksmatt** [comment]
Thanks, Mte90
